format_version: 3
pipelines:
  acceptance_tests_yaml:
    group: Development
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/gocd-demo/jy_functional_tests.git
        shallow_clone: false
        auto_update: true
        branch: master
      installers:
        pipeline: installers_yaml
        stage: defaultStage
        name: installers
    stages:
    - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob:
            timeout: 0
            elastic_profile_id: docker-ruby
            tasks:
            - exec:
                command: ./run_acceptance_tests.rb
                run_if: passed
