format_version: 3
pipelines:
  deploy_to_qa_yaml:
    group: QualityGates
    template: deploy_and_test
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/gocd-demo/jy_functional_tests.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: functional_tests
      publish_installers:
        pipeline: publish_installers
        stage: defaultStage
        name: publish_installers
    parameters:
      INSTALLER_PIPELINE: publish_installers
