format_version: 3
pipelines:
  deploy_to_prod:
    group: Production
    template: deploy_and_test
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      deployment_scripts:
        git: https://github.com/gocd-demo/jy_deployment_scripts.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: deployment_scripts
        name: deployment_scripts
      functional_tests:
        git: https://github.com/gocd-demo/jy_functional_tests.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: functional_tests
        name: functional_tests
      qa_dependency:
        pipeline: deploy_to_qa
        stage: run_user_tests
        name: qa_dependency
      performance_tests_dependency:
        pipeline: performance_tests
        stage: benchmark
        name: performance_tests_dependency
    parameters:
      INSTALLER_PIPELINE: publish_installers/deploy_to_qa
