format_version: 3
pipelines:
  installers_yaml:
    group: Development
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/gocd-demo/jy_main_repo.git
        shallow_clone: false
        auto_update: true
        branch: master
      build_and_test:
        pipeline: build_and_test_yaml
        stage: test
        name: build_and_test
    stages:
    - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob:
            timeout: 0
            elastic_profile_id: docker-maven
            artifacts:
            - build:
                source: target/*.jar
                destination: distribution
            tasks:
            - exec:
                arguments:
                - clean
                - package
                - -DskipTests
                command: mvn
                run_if: passed
